import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "../../../../lib/supabase/server";
import styles from "../../workspace.module.css";
const rupiah=new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0});
type Health={customer:any;projects:any[];mrr:number;score:number;risks:string[];openTickets:number;activeDomains:number};
export default async function CustomerHealthPage(){
 const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=String(claims?.claims?.sub??"");if(!userId)redirect("/login");
 const membership=await supabase.from("memberships").select("role").eq("user_id",userId).eq("status","active");if(!membership.data?.some(x=>x.role==="qira_admin"||x.role==="qira_consultant"))redirect("/client");
 const [{data:customers},{data:projects},{data:deployments},{data:domains},{data:subscriptions},{data:tickets}]=await Promise.all([(supabase as any).from("customers").select("id,display_name,customer_type"),(supabase as any).from("managed_projects").select("id,customer_id,service_status"),(supabase as any).from("project_deployments").select("project_id,status"),(supabase as any).from("project_domains").select("project_id,status,expires_on"),(supabase as any).from("project_subscriptions").select("project_id,status,billing_cycle,amount_idr"),(supabase as any).from("support_tickets").select("customer_id,status,priority")]);
 const thirty=new Date();thirty.setDate(thirty.getDate()+30);
 const health:Health[]=(customers??[]).map((customer:any)=>{const cp=(projects??[]).filter((x:any)=>x.customer_id===customer.id),ids=new Set(cp.map((x:any)=>x.id)),cd=(deployments??[]).filter((x:any)=>ids.has(x.project_id)),dm=(domains??[]).filter((x:any)=>ids.has(x.project_id)),ss=(subscriptions??[]).filter((x:any)=>ids.has(x.project_id)),ts=(tickets??[]).filter((x:any)=>x.customer_id===customer.id),risks:string[]=[];let score=100;
 const unhealthy=cp.filter((x:any)=>["attention","suspended"].includes(x.service_status)).length;if(unhealthy){score-=unhealthy*20;risks.push(unhealthy+" project perlu perhatian")}const errors=cd.filter((x:any)=>x.status==="error").length;if(errors){score-=errors*20;risks.push(errors+" deployment error")}const expiring=dm.filter((x:any)=>x.expires_on&&new Date(x.expires_on)<=thirty).length;if(expiring){score-=expiring*15;risks.push(expiring+" domain ≤30 hari")}const overdue=ss.filter((x:any)=>x.status==="past_due").length;if(overdue){score-=overdue*20;risks.push(overdue+" subscription past due")}const open=ts.filter((x:any)=>!["resolved","closed"].includes(x.status)),urgent=open.filter((x:any)=>x.priority==="urgent").length;if(urgent){score-=urgent*15;risks.push(urgent+" tiket urgent")}else if(open.length>=3){score-=10;risks.push(open.length+" tiket terbuka")}if(!cp.length){score-=25;risks.push("Belum ada project")}const mrr=ss.filter((x:any)=>x.status==="active").reduce((sum:number,x:any)=>sum+(x.billing_cycle==="monthly"?x.amount_idr:x.billing_cycle==="quarterly"?x.amount_idr/3:x.billing_cycle==="annual"?x.amount_idr/12:0),0);return{customer,projects:cp,mrr,score:Math.max(0,score),risks,openTickets:open.length,activeDomains:dm.filter((x:any)=>x.status==="active").length}}).sort((a:Health,b:Health)=>a.score-b.score||b.mrr-a.mrr);
 const totalMrr=health.reduce((sum,x)=>sum+x.mrr,0),atRisk=health.filter(x=>x.score<70),healthy=health.filter(x=>x.score>=85);
 return <main className={styles.page}><header className={styles.header}><div><Link className={styles.brand} href="/workspace">QIRA.</Link><p>Customer Health & Revenue</p></div><Link className={styles.primaryAction} href="/workspace/services">Kembali ke Control Center</Link></header><section className={styles.hero}><p className={styles.kicker}>Portfolio intelligence</p><h1>Prioritaskan customer berdasarkan risiko dan nilai layanan.</h1><p>Skor dihitung dari project, deployment, domain, subscription, dan support.</p></section><section className={styles.businessMetrics}><article><span>Total customer</span><strong>{health.length}</strong><small>Dalam portfolio</small></article><article><span>Estimasi MRR</span><strong>{rupiah.format(Math.round(totalMrr))}</strong><small>Subscription aktif</small></article><article><span>Customer sehat</span><strong>{healthy.length}</strong><small>Skor ≥85</small></article><article><span>Perlu perhatian</span><strong>{atRisk.length}</strong><small>Skor &lt;70</small></article></section><section className={styles.panel}><div className={styles.panelHeading}><div><p className={styles.kicker}>Health ranking</p><h2>Customer paling berisiko ditampilkan dahulu</h2></div></div>{!health.length?<p className={styles.empty}>Belum ada customer untuk dinilai.</p>:health.map(item=><div className={styles.healthRow} key={item.customer.id}><div className={styles.healthScore} data-level={item.score<70?"risk":item.score<85?"watch":"healthy"}><strong>{item.score}</strong><small>/100</small></div><div><Link href={"/workspace/services/customers/"+item.customer.id}>{item.customer.display_name}</Link><p>{item.customer.customer_type} · {item.projects.length} project · {item.activeDomains} domain aktif · {item.openTickets} tiket terbuka</p><div>{item.risks.length?item.risks.map(r=><span key={r}>{r}</span>):<span className={styles.healthyTag}>Tidak ada risiko aktif</span>}</div></div><div><small>Estimasi MRR</small><strong>{rupiah.format(Math.round(item.mrr))}</strong></div></div>)}</section><section className={styles.panel}><p className={styles.scoreNote}>Skor: project bermasalah −20; deployment error −20; domain ≤30 hari −15; subscription past due −20; tiket urgent −15; ≥3 tiket terbuka −10; belum ada project −25.</p></section></main>;
}
