export type BusinessPackageId = "digital-foundation" | "growth-engine" | "connected-growth";

export interface BusinessMetric { label: string; value: string }
export interface BusinessSectorQuestion { id: string; prompt: string; answerType: "long_text"; required: boolean }
export interface BusinessImportTemplate { id: string; name: string; description: string; columns: readonly string[] }
export interface BusinessBlueprint {
  id: string;
  name: string;
  keywords: readonly string[];
  packageId: BusinessPackageId;
  packageName: string;
  headline: string;
  problem: string;
  modules: readonly string[];
  metrics: readonly BusinessMetric[];
  flow: readonly string[];
  entities: readonly string[];
  roles: readonly string[];
  rules: readonly string[];
  outputs: readonly string[];
  integrations: readonly string[];
  sectorQuestions: readonly BusinessSectorQuestion[];
  importTemplates: readonly BusinessImportTemplate[];
}

const q=(id:string,prompt:string,required=true):BusinessSectorQuestion=>({id:`sector_${id}`,prompt,answerType:"long_text",required});
const t=(id:string,name:string,description:string,columns:string[]):BusinessImportTemplate=>({id,name,description,columns});
const bp=(value:BusinessBlueprint)=>Object.freeze(value);

export const BUSINESS_BLUEPRINTS: readonly BusinessBlueprint[] = Object.freeze([
bp({id:"rental-kendaraan",name:"Rental Kendaraan",keywords:["rental","sewa mobil","sewa motor","armada"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Booking, armada, pembayaran, dan perawatan dalam satu dashboard.",problem:"Ketersediaan kendaraan, jadwal sewa, pembayaran, dan perawatan mudah bertabrakan ketika dicatat lewat chat.",modules:["Kalender booking","Status armada","Data penyewa","Pengingat kembali"],metrics:[{label:"Armada siap",value:"8"},{label:"Disewa",value:"5"},{label:"Kembali hari ini",value:"2"}],flow:["Permintaan","Cek armada","Pembayaran","Serah terima"],entities:["Armada","Pelanggan","Booking","Pembayaran","Perawatan"],roles:["Owner","Admin booking","Petugas serah terima"],rules:["Armada terisi tidak dapat dipesan","Booking aktif membutuhkan konfirmasi","Jadwal servis memblokir armada"],outputs:["Invoice","Serah terima","Laporan utilisasi"],integrations:["WhatsApp","Pembayaran","Kalender"],sectorQuestions:[q("rental_fleet","Berapa armada aktif dan apa jenis kendaraannya?"),q("rental_pricing","Bagaimana tarif, deposit, denda, dan periode sewa dihitung?"),q("rental_handover","Data apa yang wajib dicatat saat serah terima?"),q("rental_maintenance","Bagaimana jadwal servis dan kendaraan tidak tersedia ditentukan?")],importTemplates:[t("armada","Data armada","Daftar kendaraan awal",["kode_armada","jenis","merek","nomor_polisi","status","tarif_harian"]),t("pelanggan","Data pelanggan","Kontak penyewa",["nama","whatsapp","email","alamat","catatan"])]}),
bp({id:"laundry",name:"Laundry",keywords:["laundry","cuci","setrika"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Setiap cucian terlihat dari penerimaan sampai siap diambil.",problem:"Nota, berat cucian, status proses, pembayaran, dan kabar pelanggan sering dicatat terpisah.",modules:["Order digital","Status pengerjaan","Nota otomatis","Notifikasi selesai"],metrics:[{label:"Order aktif",value:"24"},{label:"Siap diambil",value:"7"},{label:"Selesai hari ini",value:"13"}],flow:["Diterima","Dicuci","Disetrika","Siap diambil"],entities:["Pelanggan","Order","Layanan","Berat","Pembayaran"],roles:["Owner","Kasir","Operator"],rules:["Order memiliki nomor unik","Status mengikuti urutan","Order selesai memicu pemberitahuan"],outputs:["Nota","Label order","Laporan harian"],integrations:["WhatsApp","Printer nota","Pembayaran"],sectorQuestions:[q("laundry_services","Apa saja layanan, satuan, harga, dan estimasi selesainya?"),q("laundry_stages","Tahapan proses apa yang digunakan dari penerimaan sampai pengambilan?"),q("laundry_receipt","Informasi apa yang wajib tampil pada nota atau label?"),q("laundry_notification","Kapan dan melalui kanal apa pelanggan diberi kabar?")],importTemplates:[t("layanan","Daftar layanan","Harga dan durasi",["kode_layanan","nama_layanan","satuan","harga","estimasi_hari"]),t("pelanggan","Data pelanggan","Kontak pelanggan",["nama","whatsapp","alamat","catatan"])]}),
bp({id:"kuliner-katering",name:"Kuliner & Katering",keywords:["katering","catering","kuliner","restoran","bakery","makanan","kue"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Pesanan, jadwal produksi, pembayaran, dan pengiriman tertata bersama.",problem:"Pesanan dari berbagai chat rawan terlewat dan kebutuhan produksi sulit dirangkum.",modules:["Katalog & pesanan","Jadwal produksi","Rekap DP","Status pengiriman"],metrics:[{label:"Pesanan aktif",value:"18"},{label:"Produksi besok",value:"6"},{label:"DP diterima",value:"12"}],flow:["Pesanan","Konfirmasi","Produksi","Pengiriman"],entities:["Pelanggan","Pesanan","Menu","Produksi","Pengiriman"],roles:["Owner","Admin order","Tim produksi"],rules:["Produksi dimulai setelah DP","Kapasitas dibatasi per tanggal","Pengiriman mengikuti produksi"],outputs:["Invoice","Daftar produksi","Surat jalan"],integrations:["WhatsApp","Kalender","Pembayaran"],sectorQuestions:[q("food_catalog","Apa saja menu, ukuran porsi, harga, dan minimum pesanannya?"),q("food_capacity","Berapa kapasitas produksi per hari dan kapan cutoff pesanan?"),q("food_payment","Bagaimana aturan DP, pelunasan, pembatalan, dan perubahan pesanan?"),q("food_delivery","Data pengiriman apa yang harus dicatat?")],importTemplates:[t("menu","Daftar menu","Produk dan harga",["kode_menu","nama_menu","satuan","harga","minimum_pesanan"]),t("pelanggan","Data pelanggan","Kontak pelanggan",["nama","whatsapp","alamat","catatan"])]}),
bp({id:"salon-kecantikan",name:"Salon & Kecantikan",keywords:["salon","barber","barbershop","spa","kecantikan","makeup"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Jadwal layanan dan pelanggan tanpa antrean chat yang membingungkan.",problem:"Reservasi, layanan, staf, dan pengingat kunjungan sulit diselaraskan manual.",modules:["Reservasi online","Kalender staf","Riwayat pelanggan","Pengingat jadwal"],metrics:[{label:"Booking hari ini",value:"11"},{label:"Slot tersedia",value:"4"},{label:"Pelanggan ulang",value:"68%"}],flow:["Pilih layanan","Pilih jadwal","Konfirmasi","Selesai"],entities:["Pelanggan","Layanan","Staf","Jadwal","Pembayaran"],roles:["Owner","Resepsionis","Staf layanan"],rules:["Staf tidak boleh bentrok","Slot terkunci setelah konfirmasi","Pengingat sebelum kunjungan"],outputs:["Konfirmasi booking","Jadwal staf","Laporan layanan"],integrations:["WhatsApp","Kalender","Pembayaran"],sectorQuestions:[q("salon_services","Apa layanan, durasi, harga, dan staf yang dapat mengerjakannya?"),q("salon_schedule","Bagaimana jam kerja, slot, istirahat, dan hari libur diatur?"),q("salon_booking","Apa aturan konfirmasi, DP, pembatalan, dan keterlambatan?"),q("salon_history","Riwayat atau preferensi pelanggan apa yang perlu disimpan?")],importTemplates:[t("layanan","Daftar layanan","Harga dan durasi",["kode_layanan","nama_layanan","durasi_menit","harga"]),t("staf","Data staf","Staf dan keahlian",["nama","whatsapp","keahlian","jadwal_kerja"])]}),
bp({id:"kontrakan-kosan",name:"Kontrakan & Kosan",keywords:["kos","kosan","kontrakan","properti","sewa kamar"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Unit, penyewa, tagihan, dan keluhan lebih mudah dipantau.",problem:"Status unit, jatuh tempo, dan calon penyewa tersebar di catatan serta WhatsApp.",modules:["Status unit","Data penyewa","Tagihan bulanan","Pengingat WhatsApp"],metrics:[{label:"Unit terisi",value:"5/8"},{label:"Jatuh tempo",value:"2"},{label:"Calon penyewa",value:"6"}],flow:["Inquiry","Survei","Pembayaran","Mulai sewa"],entities:["Unit","Penyewa","Kontrak","Tagihan","Keluhan"],roles:["Owner","Admin properti","Petugas lapangan"],rules:["Unit terisi tidak ditawarkan","Tagihan mengikuti jatuh tempo","Tunggakan memicu pengingat"],outputs:["Invoice sewa","Kwitansi","Laporan okupansi"],integrations:["WhatsApp","Pembayaran","Dokumen"],sectorQuestions:[q("property_units","Berapa unit, tipe, harga, fasilitas, dan statusnya?"),q("property_billing","Bagaimana periode sewa, deposit, jatuh tempo, dan denda diatur?"),q("property_tenant","Dokumen dan data penyewa apa yang wajib disimpan?"),q("property_complaint","Bagaimana keluhan dan perbaikan ditugaskan serta ditutup?")],importTemplates:[t("unit","Data unit","Unit dan tarif",["kode_unit","tipe","tarif","status","fasilitas"]),t("penyewa","Data penyewa","Penyewa dan kontrak",["nama","whatsapp","kode_unit","mulai_sewa","jatuh_tempo","deposit"])]}),
bp({id:"peternakan",name:"Peternakan",keywords:["ternak","ayam","sapi","kambing","peternakan"],packageId:"connected-growth",packageName:"Connected Growth",headline:"Populasi, pakan, kesehatan, biaya, dan panen terlihat per batch.",problem:"Perubahan populasi, pakan, kesehatan, biaya, serta target panen sulit dibandingkan.",modules:["Monitoring batch","Stok pakan","Catatan kesehatan","Proyeksi panen"],metrics:[{label:"Populasi",value:"1.240"},{label:"Stok pakan",value:"68%"},{label:"Mortalitas",value:"1,8%"}],flow:["Masuk batch","Perawatan","Sampling","Panen"],entities:["Batch","Populasi","Pakan","Kesehatan","Bobot","Biaya"],roles:["Owner","Kepala kandang","Petugas"],rules:["Mortalitas di atas batas memicu alarm","Pakan mengurangi stok","Sampling memperbarui proyeksi"],outputs:["Log kandang","Laporan batch","Proyeksi panen"],integrations:["WhatsApp","Impor data","Ekspor laporan"],sectorQuestions:[q("farm_batch","Bagaimana batch, kandang, populasi awal, dan target panen ditetapkan?"),q("farm_feed","Jenis pakan, stok minimum, dan pencatatan konsumsi seperti apa?"),q("farm_health","Parameter kesehatan dan batas alarm apa yang digunakan?"),q("farm_sampling","Seberapa sering sampling dan data apa yang dicatat?")],importTemplates:[t("batch","Data batch","Batch aktif",["kode_batch","lokasi","tanggal_mulai","populasi_awal","target_panen"]),t("pakan","Data pakan","Stok awal",["kode_pakan","nama_pakan","satuan","stok_awal","stok_minimum"])]}),
bp({id:"perkebunan",name:"Perkebunan",keywords:["kebun","perkebunan","tani","pertanian","tanam"],packageId:"connected-growth",packageName:"Connected Growth",headline:"Blok, jadwal lapangan, bahan, biaya, dan panen dalam satu pandangan.",problem:"Jadwal lapangan dan biaya per blok sulit dievaluasi saat pencatatan tersebar.",modules:["Dashboard blok","Kalender aktivitas","Tenaga kerja","Estimasi panen"],metrics:[{label:"Blok aktif",value:"3"},{label:"Tugas hari ini",value:"4"},{label:"Siap panen",value:"1"}],flow:["Tanam","Perawatan","Sampling","Panen"],entities:["Blok","Tanaman","Aktivitas","Tenaga kerja","Bahan","Panen"],roles:["Owner","Koordinator","Mandor"],rules:["Aktivitas mengikuti jadwal blok","Tugas terlambat memicu pengingat","Bahan tercatat per lokasi"],outputs:["Jadwal kerja","Biaya blok","Estimasi panen"],integrations:["WhatsApp","Foto lapangan","Ekspor laporan"],sectorQuestions:[q("plantation_blocks","Apa saja blok, luas, komoditas, umur, dan kondisinya?"),q("plantation_activity","Aktivitas rutin dan interval perawatannya seperti apa?"),q("plantation_material","Bahan dan tenaga kerja apa yang dicatat per blok?"),q("plantation_harvest","Bagaimana sampling dan estimasi panen dilakukan?")],importTemplates:[t("blok","Data blok","Blok kebun",["kode_blok","luas","komoditas","tanggal_tanam","status"]),t("bahan","Data bahan","Stok bahan",["kode_bahan","nama_bahan","satuan","stok_awal","stok_minimum"])]}),
bp({id:"tambak-budidaya",name:"Tambak & Budidaya Ikan",keywords:["tambak","ikan","lele","udang","kolam"],packageId:"connected-growth",packageName:"Connected Growth",headline:"Kolam, kualitas air, pakan, pertumbuhan, dan panen terpantau.",problem:"Parameter air dan penggunaan pakan tidak cepat menunjukkan kondisi yang memerlukan tindakan.",modules:["Monitoring kolam","Kualitas air","Pakan harian","Estimasi panen"],metrics:[{label:"Kolam aktif",value:"4"},{label:"Air stabil",value:"3/4"},{label:"Panen terdekat",value:"33 hari"}],flow:["Tebar","Perawatan","Sampling","Panen"],entities:["Kolam","Kualitas air","Pakan","Sampling","Kesehatan","Panen"],roles:["Owner","Koordinator kolam","Petugas"],rules:["Parameter di luar batas memicu alarm","Pakan tercatat per kolam","Sampling memperbarui proyeksi"],outputs:["Log kolam","Pertumbuhan","Proyeksi panen"],integrations:["WhatsApp","Sensor/impor","Ekspor laporan"],sectorQuestions:[q("pond_profile","Apa saja kolam, luas, komoditas, tanggal tebar, dan populasi awal?"),q("pond_water","Parameter kualitas air dan batas amannya apa?"),q("pond_feed","Bagaimana jadwal serta jumlah pemberian pakan dicatat?"),q("pond_sampling","Seberapa sering sampling dan bagaimana target panen dihitung?")],importTemplates:[t("kolam","Data kolam","Kolam aktif",["kode_kolam","komoditas","tanggal_tebar","populasi_awal","target_panen"]),t("pakan","Data pakan","Stok pakan",["kode_pakan","nama_pakan","satuan","stok_awal","stok_minimum"])]}),
bp({id:"bengkel",name:"Bengkel Kendaraan",keywords:["bengkel","servis motor","servis mobil","sparepart","oli"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Antrean servis, mekanik, sparepart, dan riwayat kendaraan tertata.",problem:"Keluhan, pekerjaan mekanik, sparepart, dan status servis sulit dipantau manual.",modules:["Antrean servis","Work order","Stok sparepart","Riwayat kendaraan"],metrics:[{label:"Servis aktif",value:"9"},{label:"Menunggu sparepart",value:"2"},{label:"Selesai hari ini",value:"7"}],flow:["Daftar","Pemeriksaan","Pengerjaan","Serah terima"],entities:["Pelanggan","Kendaraan","Work order","Mekanik","Sparepart","Pembayaran"],roles:["Owner","Admin servis","Mekanik"],rules:["Kendaraan memiliki work order","Sparepart mengurangi stok","Selesai setelah pemeriksaan"],outputs:["Estimasi","Invoice","Riwayat kendaraan"],integrations:["WhatsApp","Printer nota","Pembayaran"],sectorQuestions:[q("workshop_services","Apa jenis servis, tarif jasa, dan estimasi waktunya?"),q("workshop_inspection","Apa checklist pemeriksaan dan persetujuan pelanggan?"),q("workshop_parts","Bagaimana sparepart, stok minimum, dan harga dicatat?"),q("workshop_warranty","Apakah ada garansi jasa atau sparepart?")],importTemplates:[t("layanan","Daftar layanan","Jasa bengkel",["kode_layanan","nama_layanan","tarif","estimasi_menit"]),t("sparepart","Data sparepart","Stok awal",["kode_barang","nama_barang","satuan","stok_awal","stok_minimum","harga_jual"])]}),
bp({id:"warung-kelontong",name:"Warung & Toko Kelontong",keywords:["warung","kelontong","sembako","minimarket","ritel"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Penjualan, stok prioritas, pemasok, dan utang-piutang mudah dipantau.",problem:"Pemilik sulit mengetahui barang cepat habis, pembelian, dan bon pelanggan bersamaan.",modules:["Penjualan sederhana","Stok prioritas","Pemasok","Utang-piutang"],metrics:[{label:"Transaksi hari ini",value:"46"},{label:"Stok menipis",value:"8"},{label:"Piutang aktif",value:"5"}],flow:["Barang masuk","Penjualan","Stok berubah","Rekap"],entities:["Produk prioritas","Penjualan","Pembelian","Pemasok","Utang","Piutang"],roles:["Owner","Kasir","Pembelian"],rules:["Penjualan mengurangi stok","Stok minimum memicu belanja","Bon memiliki jatuh tempo"],outputs:["Rekap harian","Daftar belanja","Utang-piutang"],integrations:["Printer nota","Impor data","Pembayaran"],sectorQuestions:[q("retail_priority","Produk prioritas apa yang perlu dipantau stoknya?"),q("retail_sales","Bagaimana penjualan dan metode pembayaran dicatat?"),q("retail_supplier","Bagaimana pembelian serta jatuh tempo pemasok?"),q("retail_credit","Bagaimana aturan bon dan penagihannya?")],importTemplates:[t("produk","Produk prioritas","Barang yang dipantau",["kode_produk","nama_produk","satuan","stok_awal","stok_minimum","harga_jual"]),t("pemasok","Data pemasok","Kontak pemasok",["nama","whatsapp","alamat","jatuh_tempo_hari"])]}),
bp({id:"penjahit-fashion",name:"Penjahit & Fashion",keywords:["penjahit","jahit","konveksi","fashion","butik","pakaian"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Pesanan, ukuran, bahan, produksi, dan tenggat tersusun per pelanggan.",problem:"Ukuran, model, pembayaran, dan jadwal rawan tertukar di buku dan chat.",modules:["Pesanan pelanggan","Ukuran & desain","Status produksi","Jadwal selesai"],metrics:[{label:"Pesanan aktif",value:"21"},{label:"Selesai minggu ini",value:"8"},{label:"Menunggu fitting",value:"4"}],flow:["Pesan","Ukur","Produksi","Fitting"],entities:["Pelanggan","Pesanan","Ukuran","Desain","Bahan","Produksi"],roles:["Owner","Admin","Penjahit"],rules:["Pesanan memiliki ukuran dan tenggat","Produksi mengikuti tahap","Pengambilan memeriksa pembayaran"],outputs:["Nota pesanan","Kartu ukuran","Jadwal produksi"],integrations:["WhatsApp","Upload desain","Printer nota"],sectorQuestions:[q("fashion_products","Jenis pesanan, harga, dan estimasi waktu apa yang tersedia?"),q("fashion_measurement","Ukuran dan referensi desain apa yang wajib disimpan?"),q("fashion_stages","Tahap produksi dan fitting apa yang digunakan?"),q("fashion_payment","Bagaimana DP, perubahan, dan pelunasan diatur?")],importTemplates:[t("layanan","Daftar layanan","Jenis jahitan",["kode_layanan","nama_layanan","harga_mulai","estimasi_hari"]),t("pelanggan","Data pelanggan","Kontak dan ukuran awal",["nama","whatsapp","catatan_ukuran","catatan"])]}),
bp({id:"toko-online",name:"Toko Online & Reseller",keywords:["toko online","reseller","dropship","marketplace","seller"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Order, pembayaran, packing, resi, dan stok dirangkum dalam satu proses.",problem:"Order dari banyak kanal mudah terlewat saat pembayaran, packing, dan resi terpisah.",modules:["Daftar pesanan","Status pembayaran","Packing & resi","Stok produk"],metrics:[{label:"Pesanan baru",value:"17"},{label:"Siap dikirim",value:"11"},{label:"Perlu tindak lanjut",value:"3"}],flow:["Order","Bayar","Packing","Kirim"],entities:["Produk","Pesanan","Pembayaran","Packing","Resi","Pelanggan"],roles:["Owner","Admin order","Tim packing"],rules:["Order lunas masuk packing","Resi terhubung ke order","Penjualan mengurangi stok"],outputs:["Daftar packing","Label pengiriman","Laporan penjualan"],integrations:["Marketplace","WhatsApp","Ekspedisi"],sectorQuestions:[q("online_channels","Dari kanal apa saja pesanan masuk?"),q("online_catalog","Bagaimana produk, variasi, dan stok dikelola?"),q("online_fulfillment","Bagaimana alur bayar, packing, resi, dan pengiriman?"),q("online_exception","Bagaimana pembatalan, retur, dan komplain ditangani?")],importTemplates:[t("produk","Data produk","Katalog awal",["sku","nama_produk","variasi","stok_awal","harga"]),t("pesanan","Pesanan aktif","Order yang belum selesai",["nomor_order","tanggal","pelanggan","sku","jumlah","status_bayar","status_kirim"])]}),
bp({id:"jasa-servis",name:"Jasa Servis & Teknisi",keywords:["servis ac","service ac","elektronik","teknisi","reparasi alat"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Permintaan servis, teknisi, jadwal, biaya, dan garansi terlihat jelas.",problem:"Alamat, keluhan, teknisi, biaya, dan kunjungan ulang tersebar di WhatsApp.",modules:["Tiket servis","Jadwal teknisi","Estimasi biaya","Garansi pekerjaan"],metrics:[{label:"Tiket aktif",value:"14"},{label:"Kunjungan hari ini",value:"6"},{label:"Garansi aktif",value:"9"}],flow:["Laporan","Jadwal","Perbaikan","Konfirmasi"],entities:["Tiket","Pelanggan","Perangkat","Teknisi","Sparepart","Garansi"],roles:["Owner","Admin","Teknisi"],rules:["Tiket memiliki jadwal","Biaya perlu persetujuan","Kunjungan ulang memeriksa garansi"],outputs:["Work order","Invoice","Kartu garansi"],integrations:["WhatsApp","Lokasi","Pembayaran"],sectorQuestions:[q("service_types","Apa jenis layanan, tarif, dan area layanannya?"),q("service_dispatch","Bagaimana teknisi dan jadwal kunjungan ditentukan?"),q("service_approval","Bagaimana estimasi dan persetujuan biaya dilakukan?"),q("service_warranty","Bagaimana garansi dan kunjungan ulang dikelola?")],importTemplates:[t("layanan","Daftar layanan","Jasa dan tarif",["kode_layanan","nama_layanan","tarif_mulai","estimasi_menit"]),t("teknisi","Data teknisi","Teknisi dan wilayah",["nama","whatsapp","keahlian","wilayah"])]}),
bp({id:"percetakan",name:"Percetakan & Fotokopi",keywords:["percetakan","fotocopy","fotokopi","sablon","printing"],packageId:"growth-engine",packageName:"Growth Engine",headline:"File, spesifikasi, antrean produksi, dan pembayaran terhubung per order.",problem:"Ukuran, bahan, jumlah, file, dan tenggat mudah tertukar dari banyak chat.",modules:["Order cetak","File & spesifikasi","Antrean produksi","Pengambilan"],metrics:[{label:"Antrean order",value:"16"},{label:"Diproduksi",value:"7"},{label:"Siap diambil",value:"5"}],flow:["Kirim file","Konfirmasi","Produksi","Ambil"],entities:["Order","File","Spesifikasi","Mesin","Produksi","Pembayaran"],roles:["Owner","Admin order","Operator"],rules:["Produksi menunggu file final","Antrean mengikuti tenggat","Selesai menunggu pembayaran"],outputs:["Nota order","Job sheet","Daftar pengambilan"],integrations:["Upload file","WhatsApp","Printer nota"],sectorQuestions:[q("print_services","Apa jenis cetak, bahan, ukuran, finishing, dan harganya?"),q("print_file","Bagaimana file, proof, revisi, dan persetujuan dikelola?"),q("print_queue","Bagaimana prioritas antrean dan kapasitas mesin?"),q("print_pickup","Bagaimana pembayaran, pengambilan, atau pengiriman?")],importTemplates:[t("layanan","Daftar layanan","Produk cetak",["kode_layanan","nama_layanan","satuan","harga_mulai","estimasi"]),t("pelanggan","Data pelanggan","Kontak pelanggan",["nama","whatsapp","email","catatan"])]}),
bp({id:"homestay",name:"Homestay & Penginapan",keywords:["homestay","penginapan","guest house","hotel kecil","villa"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Kamar, reservasi, tamu, pembayaran, dan housekeeping terhubung.",problem:"Reservasi dari berbagai kanal dapat berbenturan dan status kamar tidak konsisten.",modules:["Kalender kamar","Data tamu","Check-in/out","Housekeeping"],metrics:[{label:"Terisi",value:"8/12"},{label:"Check-in hari ini",value:"3"},{label:"Perlu dibersihkan",value:"2"}],flow:["Reservasi","Check-in","Menginap","Check-out"],entities:["Kamar","Reservasi","Tamu","Pembayaran","Check-in","Housekeeping"],roles:["Owner","Resepsionis","Housekeeping"],rules:["Kamar terisi tidak dipesan","Check-out membuat tugas bersih","Check-in perlu data tamu"],outputs:["Konfirmasi reservasi","Kwitansi","Laporan okupansi"],integrations:["WhatsApp","Kalender","Pembayaran"],sectorQuestions:[q("stay_rooms","Apa tipe kamar, kapasitas, tarif, fasilitas, dan jumlahnya?"),q("stay_booking","Dari kanal apa reservasi masuk dan bagaimana konfirmasinya?"),q("stay_checkin","Data apa yang wajib saat check-in dan check-out?"),q("stay_housekeeping","Bagaimana status kebersihan dan perawatan kamar?")],importTemplates:[t("kamar","Data kamar","Kamar dan tarif",["kode_kamar","tipe","kapasitas","tarif","status","fasilitas"]),t("reservasi","Reservasi aktif","Booking mendatang",["nomor_reservasi","nama_tamu","whatsapp","kode_kamar","check_in","check_out","status_bayar"])]}),
bp({id:"bimbingan-belajar",name:"Kursus, Pelatihan & Sertifikasi",keywords:["bimbel","les privat","kursus","pelatihan","training","sertifikasi","sertifikat","lpk","lembaga sertifikasi","asesmen","kelas"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Program, batch, peserta, trainer, asesmen, dan sertifikat terkelola dalam satu dashboard.",problem:"Pendaftaran peserta, jadwal batch, kehadiran, penilaian, pembayaran, dan penerbitan sertifikat sering dikelola terpisah sehingga status setiap peserta sulit dipantau.",modules:["Katalog & batch pelatihan","Peserta & perusahaan pengirim","Kehadiran & materi","Asesmen & kelulusan","Sertifikat digital & verifikasi"],metrics:[{label:"Peserta aktif",value:"84"},{label:"Batch berjalan",value:"7"},{label:"Sertifikat terbit",value:"62"}],flow:["Pendaftaran","Penjadwalan","Pelatihan","Asesmen","Sertifikasi"],entities:["Program","Batch","Peserta","Perusahaan","Trainer","Kehadiran","Asesmen","Sertifikat","Pembayaran"],roles:["Owner","Admin pelatihan","Trainer","Asesor"],rules:["Trainer dan ruang tidak boleh bentrok","Kehadiran dicatat per sesi","Kelulusan mengikuti nilai dan kehadiran minimum","Sertifikat hanya terbit setelah peserta lulus","Nomor sertifikat harus unik dan dapat diverifikasi"],outputs:["Jadwal & daftar peserta","Rekap kehadiran","Hasil asesmen","Invoice pelatihan","Sertifikat digital dengan QR verifikasi"],integrations:["WhatsApp","Kalender","Pembayaran","Email","QR verifikasi"],sectorQuestions:[q("course_programs","Apa saja program pelatihan atau sertifikasi, durasi, biaya, kapasitas, dan kompetensi akhirnya?"),q("course_batches","Bagaimana batch, trainer atau asesor, jadwal, lokasi, dan perusahaan pengirim diatur?"),q("course_assessment","Bagaimana kehadiran, pre-test, post-test, asesmen, dan batas kelulusan ditentukan?"),q("course_certificate","Bagaimana nomor sertifikat, masa berlaku, QR verifikasi, dan perpanjangan dikelola?")],importTemplates:[t("peserta","Data peserta","Peserta dan perusahaan pengirim",["id_peserta","nama","whatsapp","email","perusahaan","program","batch","status"]),t("program","Data program & batch","Program, jadwal, dan trainer",["kode_program","nama_program","kode_batch","tanggal_mulai","tanggal_selesai","trainer","kapasitas","biaya"])]}),
bp({id:"depot-air",name:"Depot Air Minum",keywords:["depot air","air isi ulang","galon","depot minum"],packageId:"growth-engine",packageName:"Growth Engine",headline:"Pesanan galon, pelanggan, rute antar, dan pembayaran terpantau.",problem:"Pesanan antar, alamat, galon pinjaman, dan pembayaran mengandalkan chat atau ingatan.",modules:["Pesanan galon","Rute pengantaran","Data pelanggan","Galon & pembayaran"],metrics:[{label:"Pesanan hari ini",value:"38"},{label:"Dalam pengantaran",value:"12"},{label:"Galon dipinjam",value:"21"}],flow:["Pesan","Siapkan","Antar","Konfirmasi"],entities:["Pesanan","Pelanggan","Alamat","Kurir","Galon","Pembayaran"],roles:["Owner","Admin pesanan","Kurir"],rules:["Pesanan memiliki area","Galon keluar-kembali tercatat","Selesai setelah konfirmasi"],outputs:["Daftar antar","Nota","Rekap galon"],integrations:["WhatsApp","Lokasi","Printer nota"],sectorQuestions:[q("water_products","Apa jenis air, ukuran, harga, dan deposit galon?"),q("water_delivery","Bagaimana area, jadwal, biaya, dan pembagian kurir?"),q("water_container","Bagaimana galon milik pelanggan dan pinjaman dicatat?"),q("water_payment","Bagaimana pembayaran tunai, transfer, atau piutang?")],importTemplates:[t("pelanggan","Data pelanggan","Alamat pengantaran",["kode_pelanggan","nama","whatsapp","alamat","area","galon_pinjaman"]),t("produk","Data produk","Jenis air dan harga",["kode_produk","nama_produk","harga","deposit_galon"])]}),
bp({id:"kerajinan-furnitur",name:"Kerajinan & Furnitur",keywords:["kerajinan","mebel","furniture","furnitur","pengrajin","souvenir"],packageId:"connected-growth",packageName:"Connected Growth",headline:"Pesanan khusus, bahan, produksi, biaya, dan tenggat dapat dipantau.",problem:"Spesifikasi, bahan, progres, serta biaya sulit dibandingkan untuk setiap pesanan.",modules:["Pesanan custom","Bahan baku","Tahap produksi","Biaya pesanan"],metrics:[{label:"Pesanan aktif",value:"13"},{label:"Dalam produksi",value:"8"},{label:"Jatuh tempo",value:"4"}],flow:["Desain","Persetujuan","Produksi","Pengiriman"],entities:["Pesanan","Desain","Bahan","Produksi","Biaya","Pengiriman"],roles:["Owner","Admin proyek","Tim produksi"],rules:["Produksi setelah desain disetujui","Bahan masuk biaya order","Pengiriman setelah QC"],outputs:["Penawaran","Job sheet","Biaya pesanan"],integrations:["Upload desain","WhatsApp","Ekspor laporan"],sectorQuestions:[q("craft_order","Apa spesifikasi, ukuran, bahan, dan pilihan custom?"),q("craft_approval","Bagaimana desain, revisi, dan persetujuan pelanggan?"),q("craft_production","Apa tahap produksi, QC, dan estimasi waktunya?"),q("craft_cost","Bagaimana bahan, tenaga, DP, dan pelunasan dicatat?")],importTemplates:[t("bahan","Data bahan","Stok bahan",["kode_bahan","nama_bahan","satuan","stok_awal","stok_minimum","harga"]),t("pesanan","Pesanan aktif","Order berjalan",["nomor_pesanan","pelanggan","deskripsi","tanggal_selesai","status","dp"])]}),
bp({id:"event-dekorasi",name:"Event & Dekorasi",keywords:["event organizer","wedding organizer","dekorasi","wedding","acara"],packageId:"connected-growth",packageName:"Connected Growth",headline:"Klien, jadwal acara, vendor, tugas, dan pembayaran terkoordinasi.",problem:"Detail acara, perubahan, vendor, perlengkapan, dan PIC terlewat di banyak grup chat.",modules:["Proyek acara","Timeline tugas","Vendor & perlengkapan","Pembayaran klien"],metrics:[{label:"Acara aktif",value:"6"},{label:"Tugas minggu ini",value:"19"},{label:"Menunggu approval",value:"4"}],flow:["Brief","Persiapan","Pelaksanaan","Penutupan"],entities:["Klien","Acara","Tugas","Vendor","Perlengkapan","Pembayaran"],roles:["Owner","Project manager","Tim acara"],rules:["Tugas memiliki PIC","Vendor perlu konfirmasi","Checklist selesai sebelum acara"],outputs:["Timeline","Checklist","Laporan anggaran"],integrations:["WhatsApp","Kalender","Dokumen"],sectorQuestions:[q("event_package","Apa paket, layanan, batas revisi, dan harga dasarnya?"),q("event_timeline","Apa milestone serta checklist wajib setiap acara?"),q("event_vendor","Bagaimana vendor, perlengkapan, dan pembayaran dikelola?"),q("event_change","Bagaimana perubahan scope dan biaya tambahan disetujui?")],importTemplates:[t("vendor","Data vendor","Vendor dan layanan",["kode_vendor","nama","layanan","whatsapp","harga_referensi"]),t("perlengkapan","Data perlengkapan","Inventaris acara",["kode_barang","nama_barang","jumlah","kondisi","lokasi"])]}),
bp({id:"kontraktor-renovasi",name:"Kontraktor & Renovasi",keywords:["kontraktor","renovasi","tukang bangunan","proyek bangunan","interior"],packageId:"connected-growth",packageName:"Connected Growth",headline:"Proyek, progres, material, tenaga kerja, dan pembayaran terlihat per lokasi.",problem:"Progres, material, perubahan pekerjaan, dan tagihan sulit dipantau tanpa laporan seragam.",modules:["Dashboard proyek","Progres lapangan","Material & biaya","Termin pembayaran"],metrics:[{label:"Proyek aktif",value:"5"},{label:"Tugas terlambat",value:"3"},{label:"Termin minggu ini",value:"2"}],flow:["Survei","Penawaran","Pelaksanaan","Serah terima"],entities:["Proyek","Pekerjaan","Progres","Material","Tenaga kerja","Termin"],roles:["Owner","Site manager","Admin proyek"],rules:["Progres perlu bukti","Material per proyek","Termin mengikuti progres"],outputs:["Laporan progres","Rekap material","Invoice termin"],integrations:["Foto lapangan","WhatsApp","Ekspor laporan"],sectorQuestions:[q("project_scope","Bagaimana pekerjaan, volume, harga, dan perubahan scope dicatat?"),q("project_progress","Bagaimana progres, foto, approval, dan keterlambatan dilaporkan?"),q("project_material","Bagaimana pembelian, penerimaan, dan pemakaian material?"),q("project_billing","Bagaimana termin klien, vendor, dan tenaga kerja?")],importTemplates:[t("proyek","Data proyek","Proyek aktif",["kode_proyek","nama_proyek","klien","lokasi","tanggal_mulai","target_selesai","nilai"]),t("material","Data material","Material awal",["kode_material","nama_material","satuan","stok_awal","harga"])]})
]);

export function getBusinessBlueprint(id:string|undefined):BusinessBlueprint|undefined {
  return id ? BUSINESS_BLUEPRINTS.find(item=>item.id===id) : undefined;
}

export function findBusinessBlueprint(input:string):BusinessBlueprint|undefined {
  const normalized=input.toLowerCase();
  return BUSINESS_BLUEPRINTS.find(item=>item.keywords.some(keyword=>normalized.includes(keyword)));
}

export function businessBlueprintSnapshot(blueprint:BusinessBlueprint){
  return {id:blueprint.id,name:blueprint.name,packageId:blueprint.packageId,modules:[...blueprint.modules],entities:[...blueprint.entities],roles:[...blueprint.roles],rules:[...blueprint.rules],outputs:[...blueprint.outputs],integrations:[...blueprint.integrations],importTemplates:blueprint.importTemplates.map(item=>({...item,columns:[...item.columns]}))};
}
