import Link from "next/link";
import {redirect} from "next/navigation";
import {createClient} from "../../../lib/supabase/server";
import styles from "../workspace.module.css";

type Item={group:string;name:string;owner:string;required:boolean;configured:boolean;detail:string;steps:string[]};
export default async function ProductionReadinessPage(){
 const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();const userId=String(claims?.claims?.sub??"");if(!userId)redirect("/login");
 const membership=await supabase.from("memberships").select("role").eq("user_id",userId).eq("status","active");if(!membership.data?.some(x=>x.role==="qira_admin"))redirect("/client");
 const hasSupabaseUrl=Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL),hasPublicKey=Boolean(process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY||process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY),hasCron=Boolean(process.env.CRON_SECRET),hasBackendKey=Boolean(process.env.SUPABASE_SECRET_KEY||process.env.SUPABASE_SERVICE_ROLE_KEY),hasEmailKey=Boolean(process.env.RESEND_API_KEY),hasEmailFrom=Boolean(process.env.EMAIL_FROM),hasAppUrl=Boolean(process.env.NEXT_PUBLIC_APP_URL);
 const items:Item[]=[
  {group:"Aplikasi inti",name:"Supabase project URL",owner:"Dapat dicek otomatis",required:true,configured:hasSupabaseUrl,detail:"Alamat project database dan Auth.",steps:["Vercel → Project Settings → Environment Variables","Tambahkan NEXT_PUBLIC_SUPABASE_URL untuk Production dan Preview"]},
  {group:"Aplikasi inti",name:"Supabase publishable key",owner:"Dapat dicek otomatis",required:true,configured:hasPublicKey,detail:"Key publik untuk login dan akses berbasis RLS.",steps:["Supabase → Settings → API Keys","Tambahkan NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY di Vercel"]},
  {group:"Reminder",name:"CRON_SECRET",owner:"Mahendra",required:true,configured:hasCron,detail:"Melindungi endpoint reminder harian dari pemanggilan publik.",steps:["Buat nilai acak minimal 32 karakter","Tambahkan CRON_SECRET di Vercel Production","Redeploy production setelah menyimpan"]},
  {group:"Reminder",name:"Supabase backend secret",owner:"Mahendra",required:true,configured:hasBackendKey,detail:"Mengizinkan cron server menulis reminder tanpa sesi pengguna.",steps:["Supabase → Settings → API Keys → buat/copy Secret key","Tambahkan sebagai SUPABASE_SECRET_KEY di Vercel Production","Jangan gunakan prefix NEXT_PUBLIC_"]},
  {group:"Email",name:"Email provider API key",owner:"Mahendra",required:false,configured:hasEmailKey,detail:"Diperlukan ketika QIRA mulai mengirim notifikasi dari hello@myqira.io.",steps:["Aktifkan provider email yang dipilih","Verifikasi domain pengirim","Tambahkan RESEND_API_KEY hanya di Vercel server environment"]},
  {group:"Email",name:"Alamat pengirim QIRA",owner:"Mahendra",required:false,configured:hasEmailFrom,detail:"Identitas pengirim notifikasi pelanggan.",steps:["Set EMAIL_FROM menjadi QIRA <hello@myqira.io>","Pastikan domain sudah lolos SPF dan DKIM"]},
  {group:"Domain",name:"Production app URL",owner:"Mahendra",required:false,configured:hasAppUrl,detail:"URL canonical untuk tautan email dan callback.",steps:["Aktifkan kembali domain myqira.io atau subdomain aplikasi","Tambahkan NEXT_PUBLIC_APP_URL","Perbarui redirect URL pada Supabase Auth"]},
  {group:"Domain",name:"DNS myqira.io",owner:"Mahendra",required:false,configured:false,detail:"Tidak bisa diverifikasi dari aplikasi tanpa akses registrar/DNS.",steps:["Tambahkan DNS sesuai instruksi Vercel","Tambahkan SPF, DKIM, dan DMARC untuk hello@myqira.io","Verifikasi domain di Vercel dan provider email"]},
  {group:"Operasional",name:"Backup & recovery policy",owner:"Mahendra + QIRA",required:false,configured:false,detail:"Tentukan backup, retensi, dan PIC pemulihan sebelum customer pertama.",steps:["Tentukan RPO/RTO sederhana","Catat siapa pemilik backup dan akses recovery","Uji restore sebelum layanan kritis"]},
  {group:"Infrastruktur",name:"Template deployment non-Vercel",owner:"QIRA saat ada kebutuhan",required:false,configured:false,detail:"Disiapkan ketika customer nyata memilih Managed VPS atau server sendiri; tidak perlu menyewa VPS sekarang.",steps:["Pilih provider sesuai workload customer","Gunakan GitHub Actions + SSH/deploy key terbatas","Siapkan HTTPS, firewall, backup, monitoring, dan rollback"]},
 ];
 const required=items.filter(x=>x.required),ready=required.filter(x=>x.configured).length;
 return <main className={styles.page}><header className={styles.header}><div><Link className={styles.brand} href="/workspace">QIRA.</Link><p>Production Readiness</p></div><Link className={styles.primaryAction} href="/workspace">Kembali ke Workspace</Link></header><section className={styles.hero}><p className={styles.kicker}>Configuration control</p><h1>Apa yang masih perlu disiapkan agar QIRA berjalan sempurna.</h1><p>Nilai secret tidak pernah ditampilkan. Halaman ini hanya memeriksa apakah konfigurasi tersedia di server.</p></section><section className={styles.readinessSummary}><div><strong>{ready}/{required.length}</strong><span>Konfigurasi wajib siap</span></div><div className={styles.readinessBar}><i style={{width:(ready/required.length*100)+"%"}}/></div></section><section className={styles.panel}>{items.map((item,index)=><article className={styles.readinessItem} key={item.name}><div className={item.configured?styles.readyDot:item.required?styles.blockedDot:styles.pendingDot}>{item.configured?"✓":index+1}</div><div><p>{item.group} · {item.owner}</p><h2>{item.name}</h2><span>{item.detail}</span><details><summary>Langkah setup</summary><ol>{item.steps.map(step=><li key={step}>{step}</li>)}</ol></details></div><div><span className={item.configured?styles.readyBadge:item.required?styles.urgentBadge:styles.neutralBadge}>{item.configured?"Configured":item.required?"Required":"Planned"}</span></div></article>)}</section></main>;
}
