import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "../../../../lib/supabase/server";
import styles from "../../workspace.module.css";
import { addDeployment,addDomain,addSubscription,addTicket } from "./actions";

export default async function ServiceRecordsPage({searchParams}:{searchParams:Promise<{saved?:string;error?:string}>}){
 const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();if(!claims?.claims?.sub)redirect("/login");
 const membership=await supabase.from("memberships").select("role").eq("user_id",String(claims.claims.sub)).eq("status","active");
 if(!membership.data?.some(item=>item.role==="qira_admin"||item.role==="qira_consultant"))redirect("/client");
 const [{data:projects},{data:customers}]=await Promise.all([(supabase as any).from("managed_projects").select("id,name,customer_id").order("name"),(supabase as any).from("customers").select("id,display_name").order("display_name")]);
 const params=await searchParams;const projectOptions=(projects??[]).map((p:any)=><option key={p.id} value={p.id}>{p.name}</option>);
 return <main className={styles.page}>
  <header className={styles.header}><div><Link className={styles.brand} href="/workspace">QIRA.</Link><p>Service Record Center</p></div><Link className={styles.primaryAction} href="/workspace/services">Kembali ke Control Center</Link></header>
  <section className={styles.hero}><p className={styles.kicker}>Operasional layanan</p><h1>Catat komponen layanan setiap customer.</h1><p>Tambahkan domain, status deployment, recurring subscription, dan support ticket tanpa keluar dari workspace QIRA.</p></section>
  {params.saved?<p className={styles.formSuccess}>Record {params.saved} berhasil disimpan.</p>:null}{params.error?<p className={styles.formError}>Record belum berhasil disimpan. Periksa data dan coba kembali.</p>:null}
  {!projects?.length?<section className={styles.panel}><p className={styles.empty}>Belum ada project. Lakukan <Link href="/workspace/services/onboard">onboarding customer</Link> terlebih dahulu.</p></section>:
  <div className={styles.recordGrid}>
   <form action={addDomain} className={styles.recordForm}><h2>Domain</h2><label>Project<select name="projectId" required><option value="">Pilih project</option>{projectOptions}</select></label><label>Hostname<input name="hostname" required placeholder="contohusaha.com"/></label><label>Registrar<input name="registrar" placeholder="Cloudflare, Niagahoster..."/></label><label>Ownership<select name="ownership"><option value="customer">Milik customer</option><option value="qira">Milik QIRA</option></select></label><label>Status<select name="status"><option value="active">Active</option><option value="pending">Pending</option><option value="expiring">Expiring</option><option value="issue">Issue</option></select></label><label>Expiry<input name="expiresOn" type="date"/></label><label className={styles.checkLabel}><input name="autoRenew" type="checkbox"/> Auto-renew</label><button type="submit">Simpan domain</button></form>
   <form action={addDeployment} className={styles.recordForm}><h2>Deployment</h2><label>Project<select name="projectId" required><option value="">Pilih project</option>{projectOptions}</select></label><label>Provider<select name="provider"><option value="vercel">Vercel</option><option value="customer_infrastructure">Infrastruktur customer</option><option value="other">Lainnya</option></select></label><label>Status<select name="status"><option value="ready">Ready</option><option value="building">Building</option><option value="error">Error</option><option value="unknown">Unknown</option></select></label><label>Deployment URL<input name="deploymentUrl" type="url" placeholder="https://..."/></label><label>Reference<input name="deploymentRef" placeholder="Commit atau deployment ID"/></label><button type="submit">Simpan deployment</button></form>
   <form action={addSubscription} className={styles.recordForm}><h2>Subscription</h2><label>Project<select name="projectId" required><option value="">Pilih project</option>{projectOptions}</select></label><label>Nama layanan<input name="name" required minLength={2} placeholder="Managed service QIRA"/></label><label>Nominal (Rp)<input name="amount" type="number" min="0" step="1000" required/></label><label>Siklus<select name="billingCycle"><option value="monthly">Bulanan</option><option value="quarterly">3 bulanan</option><option value="annual">Tahunan</option><option value="one_time">Sekali bayar</option></select></label><label>Status<select name="status"><option value="active">Active</option><option value="trial">Trial</option><option value="past_due">Past due</option><option value="paused">Paused</option></select></label><label>Mulai<input name="startedOn" type="date"/></label><label>Tagihan berikut<input name="nextBillingOn" type="date"/></label><button type="submit">Simpan subscription</button></form>
   <form action={addTicket} className={styles.recordForm}><h2>Support Ticket</h2><label>Customer<select name="customerId" required><option value="">Pilih customer</option>{(customers??[]).map((c:any)=><option key={c.id} value={c.id}>{c.display_name}</option>)}</select></label><label>Project (opsional)<select name="projectId"><option value="">Tanpa project</option>{projectOptions}</select></label><label>Subjek<input name="subject" required minLength={3}/></label><label>Prioritas<select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></label><label>Deskripsi<textarea name="description" required minLength={3} rows={4}/></label><button type="submit">Buat tiket</button></form>
  </div>}
 </main>;
}
