import Link from "next/link";
import { redirect } from "next/navigation";
import { createClient } from "../../../../lib/supabase/server";
import styles from "../../workspace.module.css";
import {updateDeploymentStatus,updateDomainStatus,updateProjectStatus,updateSubscriptionStatus,updateTicketStatus} from "./actions";

const date=(value:string|null)=>value?new Intl.DateTimeFormat("id-ID",{dateStyle:"medium"}).format(new Date(value)):"—";
export default async function ActionCenterPage({searchParams}:{searchParams:Promise<{saved?:string;error?:string;project?:string}>}){
 const supabase=await createClient();const {data:claims}=await supabase.auth.getClaims();if(!claims?.claims?.sub)redirect("/login");
 const membership=await supabase.from("memberships").select("role").eq("user_id",String(claims.claims.sub)).eq("status","active");if(!membership.data?.some(i=>i.role==="qira_admin"||i.role==="qira_consultant"))redirect("/client");
 const horizon=new Date();horizon.setDate(horizon.getDate()+45);const horizonDate=horizon.toISOString().slice(0,10);const today=new Date().toISOString().slice(0,10);
 const [{data:projects},{data:deployments},{data:domains},{data:subscriptions},{data:tickets}]=await Promise.all([
  (supabase as any).from("managed_projects").select("id,name,service_status,next_review_on").in("service_status",["onboarding","attention","maintenance","suspended"]).order("updated_at"),
  (supabase as any).from("project_deployments").select("id,project_id,provider,deployment_url,status,checked_at").order("checked_at"),
  (supabase as any).from("project_domains").select("id,project_id,hostname,status,expires_on").order("expires_on"),
  (supabase as any).from("project_subscriptions").select("id,project_id,name,status,next_billing_on,amount_idr").order("next_billing_on"),
  (supabase as any).from("support_tickets").select("id,ticket_number,subject,priority,status,due_at").in("status",["open","in_progress","waiting_customer"]).order("due_at"),
 ]);
 const params=await searchParams;
 const readiness=(project:any)=>{const ds=(deployments??[]).filter((x:any)=>x.project_id===project.id),dm=(domains??[]).filter((x:any)=>x.project_id===project.id),ss=(subscriptions??[]).filter((x:any)=>x.project_id===project.id);const deployment=ds.some((x:any)=>x.status==="ready"),domain=!dm.length||dm.some((x:any)=>x.status==="active"),subscription=!ss.length||ss.some((x:any)=>x.status==="active"||x.status==="trial");return {deployment,domain,subscription,ready:deployment&&domain&&subscription}};
 const deploymentAlerts=(deployments??[]).filter((x:any)=>["queued","building","error","unknown"].includes(x.status));
 const domainAlerts=(domains??[]).filter((x:any)=>x.expires_on&&x.expires_on<=horizonDate);
 const billingAlerts=(subscriptions??[]).filter((x:any)=>x.next_billing_on&&x.next_billing_on<=horizonDate&&["trial","active","past_due"].includes(x.status));
 return <main className={styles.page}>
  <header className={styles.header}><div><Link className={styles.brand} href="/workspace">QIRA.</Link><p>Managed Services Action Center</p></div><Link className={styles.primaryAction} href="/workspace/services">Kembali ke Control Center</Link></header>
  <section className={styles.hero}><p className={styles.kicker}>Perlu tindakan</p><h1>Jatuh tempo, readiness, dan status layanan dalam satu antrean.</h1><p>Project hanya dapat diaktifkan setelah deployment siap dan konfigurasi domain/subscription yang digunakan sudah valid.</p></section>
  {params.saved?<p className={styles.formSuccess}>Status berhasil diperbarui.</p>:null}{params.error==="readiness"?<p className={styles.formError}>Aktivasi ditahan: lengkapi checklist readiness project terlebih dahulu.</p>:params.error?<p className={styles.formError}>Status belum berhasil diperbarui.</p>:null}
  <section className={styles.panel}><div className={styles.panelHeading}><div><p className={styles.kicker}>Activation readiness</p><h2>Checklist sebelum customer go-live</h2></div></div>
   {!projects?.length?<p className={styles.empty}>Tidak ada project yang menunggu aktivasi.</p>:(projects??[]).map((x:any)=>{const r=readiness(x);return <div className={styles.metricRow} key={`ready-${x.id}`}><div><strong>{x.name}</strong><p>Deployment {r.deployment?"✓":"—"} · Domain {r.domain?"✓":"—"} · Subscription {r.subscription?"✓":"—"}</p></div><span className={r.ready?styles.neutralBadge:styles.warningBadge}>{r.ready?"Ready to activate":"Setup belum lengkap"}</span></div>})}
  </section>
  <div className={styles.actionColumns}>
   <section className={styles.panel}><div className={styles.panelHeading}><h2>Project</h2><span className={styles.neutralBadge}>{projects?.length??0}</span></div>{!projects?.length?<p className={styles.empty}>Tidak ada project yang perlu perhatian.</p>:(projects??[]).map((x:any)=>{const r=readiness(x);return <form action={updateProjectStatus} className={styles.actionRow} key={x.id}><input type="hidden" name="id" value={x.id}/><div><strong>{x.name}</strong><small>{x.service_status} · {r.ready?"ready":"belum ready"} · review {date(x.next_review_on)}</small></div><select name="status" defaultValue={x.service_status}><option value="active" disabled={!r.ready}>Active{r.ready?"":" — lengkapi readiness"}</option><option value="attention">Attention</option><option value="maintenance">Maintenance</option><option value="suspended">Suspended</option><option value="offboarded">Offboarded</option></select><button>Simpan</button></form>})}</section>
   <section className={styles.panel}><div className={styles.panelHeading}><h2>Deployment</h2><span className={styles.warningBadge}>{deploymentAlerts.length}</span></div>{!deploymentAlerts.length?<p className={styles.empty}>Tidak ada deployment bermasalah.</p>:deploymentAlerts.map((x:any)=><form action={updateDeploymentStatus} className={styles.actionRow} key={x.id}><input type="hidden" name="id" value={x.id}/><div><strong>{x.provider} · {x.status}</strong><small>Checked {date(x.checked_at)}</small></div><select name="status" defaultValue={x.status}><option value="ready">Ready</option><option value="building">Building</option><option value="error">Error</option><option value="unknown">Unknown</option><option value="cancelled">Cancelled</option></select><button>Simpan</button></form>)}</section>
   <section className={styles.panel}><div className={styles.panelHeading}><h2>Domain ≤45 hari</h2><span className={styles.warningBadge}>{domainAlerts.length}</span></div>{!domainAlerts.length?<p className={styles.empty}>Tidak ada domain mendekati expiry.</p>:domainAlerts.map((x:any)=><form action={updateDomainStatus} className={styles.actionRow} key={x.id}><input type="hidden" name="id" value={x.id}/><div><strong>{x.hostname}</strong><small>{x.expires_on<today?"Sudah lewat":"Expiry"} · {date(x.expires_on)}</small></div><select name="status" defaultValue={x.status}><option value="active">Active</option><option value="expiring">Expiring</option><option value="expired">Expired</option><option value="issue">Issue</option></select><button>Simpan</button></form>)}</section>
   <section className={styles.panel}><div className={styles.panelHeading}><h2>Billing ≤45 hari</h2><span className={styles.neutralBadge}>{billingAlerts.length}</span></div>{!billingAlerts.length?<p className={styles.empty}>Tidak ada tagihan mendekati jatuh tempo.</p>:billingAlerts.map((x:any)=><form action={updateSubscriptionStatus} className={styles.actionRow} key={x.id}><input type="hidden" name="id" value={x.id}/><div><strong>{x.name}</strong><small>{date(x.next_billing_on)} · Rp{Number(x.amount_idr).toLocaleString("id-ID")}</small></div><select name="status" defaultValue={x.status}><option value="active">Active</option><option value="past_due">Past due</option><option value="paused">Paused</option><option value="cancelled">Cancelled</option></select><button>Simpan</button></form>)}</section>
   <section className={styles.panel}><div className={styles.panelHeading}><h2>Support terbuka</h2><span className={styles.urgentBadge}>{tickets?.length??0}</span></div>{!tickets?.length?<p className={styles.empty}>Tidak ada tiket terbuka.</p>:(tickets??[]).map((x:any)=><form action={updateTicketStatus} className={styles.actionRow} key={x.id}><input type="hidden" name="id" value={x.id}/><div><strong>{x.ticket_number} · {x.subject}</strong><small>{x.priority} · due {date(x.due_at)}</small></div><select name="status" defaultValue={x.status}><option value="open">Open</option><option value="in_progress">In progress</option><option value="waiting_customer">Waiting customer</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select><button>Simpan</button></form>)}</section>
  </div>
 </main>;
}
